root: true
parser: babel-eslint
parserOptions:
    sourceType: module
env:
    browser: true
extends: standard
rules:
    semi:
        - 2
        - always
    indent:
        - 2
    space-before-function-paren:
        - 2
        - anonymous: never
          named: always
    no-console: error
    comma-dangle: 0
    arrow-parens: 0
    one-var: 0
    func-names: 0
    generator-star-spacing: 0
    no-unused-expressions: 0
    max-len:
        - 2
        - 120
        - 4
    no-return-assign: 0
    one-var-declaration-per-line:
        - 2
        - initializations
    eqeqeq:
        - 2
        - allow-null
